version: '3'

services: 
  sde-server:
    image: sde-server:latest
    container_name: sde-server
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./grafana:/grafana
    ports:
      - 3000:3000
      - 9090:9090
      - 9100:9100